source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '13.0'

target 'iot' do
    
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/OAuth'
    pod 'FirebaseUI/Email'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestoreSwift'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
